#!/usr/bin/env python3
"""
🚀 Nongor Premium Bot - Quick Setup Script
==========================================
This script helps you set up the bot quickly.
"""

import os
import sys
from pathlib import Path

def print_header():
    print("=" * 60)
    print("🌟 NONGOR PREMIUM BOT v3.0 - SETUP (Python 3.14 Edition)")
    print("=" * 60)
    print()

def check_python_version():
    """Check if Python version is compatible."""
    if sys.version_info < (3, 8):
        print("❌ Error: Python 3.8 or higher is required!")
        print(f"   Current version: {sys.version}")
        return False
    print(f"✅ Python version: {sys.version.split()[0]}")
    return True

def check_dependencies():
    """Check if required packages are installed."""
    print("\n📦 Checking dependencies...")
    
    required = [
        'telegram',
        'dotenv',
        'pg8000', # Replaced psycopg2
        'google.generativeai',
        'requests',
        # 'matplotlib' # Disabled for Python 3.14
    ]
    
    missing = []
    for package in required:
        try:
            if package == 'telegram':
                __import__('telegram.ext')
            elif package == 'dotenv':
                __import__('dotenv')
            elif package == 'google.generativeai':
                __import__('google', fromlist=['generativeai'])
            else:
                __import__(package)
            print(f"  ✅ {package}")
        except ImportError:
            print(f"  ❌ {package} - NOT INSTALLED")
            missing.append(package)
    
    if missing:
        print(f"\n⚠️  Missing {len(missing)} package(s)")
        print("\n💡 To install, run:")
        print("   pip install --upgrade --pre -r Bot/requirements.txt")
        return False
    
    print("\n✅ All dependencies installed!")
    return True

def setup_env_file():
    """Guide user through .env file creation."""
    print("\n📝 Setting up .env file...")
    
    env_path = Path('.env')
    example_path = Path('.env.example')
    
    if env_path.exists():
        print("✅ .env file already exists.")
        # Optional: Read it to verify content
        return True
    
    print("\n📋 Let's configure your bot!")
    print("(Press Enter to skip optional fields)\n")
    
    # Get Telegram Bot Token
    print("1️⃣  TELEGRAM BOT TOKEN (Required)")
    print("   Get it from @BotFather on Telegram")
    bot_token = input("   Enter your bot token: ").strip()
    
    if not bot_token:
        print("❌ Bot token is required!")
        return False
    
    # Get Admin User IDs
    print("\n2️⃣  ADMIN USER IDs")
    print("   You can get your ID by running the bot and sending /start")
    print("   For multiple admins, separate with commas: 123,456,789")
    admin_ids = input("   Enter admin user ID(s) (or skip for now): ").strip()
    
    # Get Gemini API Key
    print("\n3️⃣  GEMINI API KEY (Optional - for AI features)")
    print("   Get it from: https://aistudio.google.com/app/apikey")
    gemini_key = input("   Enter Gemini API key (or skip): ").strip()
    
    # Get Website URL
    print("\n4️⃣  WEBSITE URL (Optional - for monitoring)")
    website_url = input("   Enter website URL (default: https://nongor-brand.vercel.app/): ").strip()
    if not website_url:
        website_url = "https://nongor-brand.vercel.app/"
    
    # Get Database URL
    print("\n5️⃣  DATABASE URL (Optional - for order/sales features)")
    print("   PostgreSQL connection string from Netlify")
    db_url = input("   Enter database URL (or skip): ").strip()
    
    # Create .env file
    env_content = f"""# Nongor Premium Bot Configuration
# Generated by setup script

# Telegram Configuration
TELEGRAM_BOT_TOKEN={bot_token}
ADMIN_USER_IDS={admin_ids if admin_ids else ''}

# AI Assistant
GEMINI_API_KEY={gemini_key if gemini_key else ''}

# Website Monitoring
WEBSITE_URL={website_url}
MONITOR_INTERVAL_SECONDS=300

# Database
NETLIFY_DATABASE_URL={db_url if db_url else ''}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    return True

def final_instructions():
    """Show final setup instructions."""
    print("\n" + "=" * 60)
    print("🎉 SETUP COMPLETE!")
    print("=" * 60)
    print("\n📋 Next steps:\n")
    print("1. Run the bot:")
    print("   python Bot/bot_v2.py")
    print()
    print("2. Open Telegram and find your bot")
    print()
    print("3. Send /start to begin!")
    print()
    print("=" * 60)

def main():
    """Main setup flow."""
    print_header()
    
    # Check Python version
    if not check_python_version():
        sys.exit(1)
    
    # Check dependencies
    deps_ok = check_dependencies()
    
    if not deps_ok:
        response = input("\n❓ Continue anyway? (y/N): ")
        if response.lower() != 'y':
            print("\n👋 Exiting. Install dependencies first!")
            sys.exit(1)
    
    # Setup .env
    if not setup_env_file():
        # print("\n❌ Setup failed!") # Don't exit if env fails, user might have manual env
        pass
    
    # Show final instructions
    final_instructions()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n👋 Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)
